### PR TITLE
Add version bound because some method signature is changed.

### PR DESCRIPTION
**Pull request by kazuki-ma**
jackson-lombok.jar compiled with jackson < 2.6 is not compatible with jackson >= 2.6.

To tell version bound to users, add version bound to build jackson-lombok with jackson 2.6.4(newest).

This PR is a reviced edition of PR https://github.com/xebia/jackson-lombok/pull/2.
It will fix Issue https://github.com/xebia/jackson-lombok/issues/1

### CODE REVIEW

**Comment by 0xR** [comment]
We need to have the tests work in order to merge this PR

**Comment by kazuki-ma** [comment]
@0xR Thank you for advices. Compatibility Test (Positive and Negative) added.
Summary is below. Full version is [here](https://gist.github.com/kazuki-ma/07e45cb8c57c2e301673)

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] jackson-lombok-parent .............................. SUCCESS [  1.104 s]
[INFO] jackson-lombok ..................................... SUCCESS [  3.200 s]
[INFO] jackson-lombok-test-2.5 ............................ SUCCESS [  1.057 s]
[INFO] jackson-lombok-test-2.6 ............................ SUCCESS [  0.673 s]
[INFO] jackson-lombok-test-2.7 ............................ SUCCESS [  0.654 s]
[INFO] ------------------------------------------------------------------------
```

**Comment by kazuki-ma** [comment]
@lightoze Bad news: `[2.6.0,2.7.0)` includes `2.7.0-rc3`. [jackson-databind/2.7.0-rc3](http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core/2.7.0-rc3)
Because they release rc in maven central for release, not as `SNAPSHOT`.
That's a reason I use `2.6.999`.

**Comment by lightoze** [comment]
You are right. `[2.6.0,2.7)` should work correctly. Anyway, my point was to make it work with future `2.6.*` releases.

**Comment by kazuki-ma** [comment]
@lightoze Sorry my miss-understanding.
Updated https://github.com/xebia/jackson-lombok/pull/4/files#diff-600376dffeb79835ede4a0b285078036R45

**Comment by devshorts** [comment]
Can we get this merged in?

**Comment by 0xR** [comment]
This is not ready to merge in. I'm not sure why we would want to break compatibility with jackson 2.4 and 2.5. It looks like we're compatible with 2.4 - 2.6.

**Comment by 0xR** [comment]
I updated the dependencies on master, maintaining compatibility with jackson 2.4 - 2.6. This is release to mvn central.

**Comment by 0xR** [comment]
In trying to make jackson-lombok compatible with 2.7 I discovered that[ Jackson now supports the `ConstructorProperties` annotation](https://github.com/FasterXML/jackson-databind/blob/master/release-notes/CREDITS) that lombok generates automatically. This makes this project obsolete.

Jackson will generate an error if you try to rename your property with a `@JsonProperty("new_name")` annotation. This is because this annotation will conflict with the `ConstructorProperties` annotation that Lombok generates. My recommendation is not to do any renaming via annotations. It makes sense to have your lombok values look like your json.

In case some1 does need renaming it can be submitted as an issue to the Jackson project.

**Pull request closed without merging**
